// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxies(arg1, arg2) {
  return window['go']['backendmanager']['ProxyManager']['AddProxies'](arg1, arg2);
}

export function GetProxies() {
  return window['go']['backendmanager']['ProxyManager']['GetProxies']();
}

export function RemoveProxies(arg1) {
  return window['go']['backendmanager']['ProxyManager']['RemoveProxies'](arg1);
}
