// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backendmanager} from '../models';

export function AddProxies(arg1:Array<string>,arg2:backendmanager.ProxyType):Promise<void>;

export function GetProxies():Promise<Array<backendmanager.Proxy>>;

export function RemoveProxies(arg1:Array<string>):Promise<void>;
