// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateQueue(arg1) {
  return window['go']['backendmanager']['QueueManager']['CreateQueue'](arg1);
}

export function DeleteQueue(arg1) {
  return window['go']['backendmanager']['QueueManager']['DeleteQueue'](arg1);
}

export function GetQueues() {
  return window['go']['backendmanager']['QueueManager']['GetQueues']();
}
