// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {accountmanager} from '../models';

export function AddAccount(arg1:accountmanager.Account):Promise<void>;

export function GetAccounts():Promise<Array<accountmanager.Account>>;

export function RemoveAccount(arg1:accountmanager.Account):Promise<void>;
