// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['accountmanager']['AccountManager']['AddAccount'](arg1);
}

export function GetAccounts() {
  return window['go']['accountmanager']['AccountManager']['GetAccounts']();
}

export function RemoveAccountByEmail(arg1) {
  return window['go']['accountmanager']['AccountManager']['RemoveAccountByEmail'](arg1);
}
