// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mc} from '../models';
import {accountmanager} from '../models';

export function AddAccounts(arg1:string,arg2:mc.AccType):Promise<void>;

export function GetAccounts():Promise<Array<accountmanager.Account>>;

export function RemoveAccountByEmail(arg1:string):Promise<void>;
