// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccounts(arg1, arg2) {
  return window['go']['backendmanager']['AccountManager']['AddAccounts'](arg1, arg2);
}

export function GetAccounts() {
  return window['go']['backendmanager']['AccountManager']['GetAccounts']();
}

export function RemoveAccountByEmail(arg1) {
  return window['go']['backendmanager']['AccountManager']['RemoveAccountByEmail'](arg1);
}
