// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backendmanager} from '../models';

export function CreateQueue(arg1:backendmanager.Queue):Promise<void>;

export function DeleteQueue(arg1:string):Promise<void>;

export function GetQueues():Promise<Array<backendmanager.Queue>>;
